---
- hosts: "all"
  become: "yes"
  remote_user: "vagrant"
  vars_files: 
    - vars.yml 
  strategy: free 


  
  tasks: 
    - name: Add google signing key
      apt_key: 
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        state: present
      when: ansible_distribution == "Ubuntu"

    - name: Add the backports repo 
      apt_repository: 
       repo: 'deb http://ftp.de.debian.org/debian wheezy-backports main'
       state: present
      when: ansible_distribution == "Ubuntu"

    - name: Add the k8 APT Repo 
      apt_repository: 
       repo: 'deb http://apt.kubernetes.io/ kubernetes-xenial main'
       state: present
      when: ansible_distribution == "Ubuntu"

    - name: install packages
      apt: 
       name: "{{ item }}" 
       state: installed 
       update_cache: true 
      with_items: "{{ packages }}" 
      when: ansible_distribution == "Ubuntu" 

    - name: get misc-scripts
      git: 
          repo: https://github.com/zanetworker/misc-scripts.git
          dest: /home/vagrant/misc-scripts
          clone: yes
          update: no

    - name: Ensure Kubernetes YUM repository
      when: ansible_distribution == 'CentOS'
      become: yes
      yum_repository:
        name: Kubernetes
        description: Kubernetes YUM repository
        baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el$releasever-$basearch-unstable
        gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg
           https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
        gpgcheck: yes
        state: present 

